### PR TITLE
Added docker installation option

### PR DESCRIPTION
**Pull request by wuisawesome**
I noticed people were having some issues getting the code to run and ran across some annoying dependency issues myself while setting up the model. I got the dependencies set up and working in docker which should cause less problems. 

If this is something you feel would be appropriate to add to the repository then feel free to do so. If not I won’t be offended :p

### CODE REVIEW

**Comment by AaronJackson** [comment]
Thanks! That's nice to have.

**Comment by nmsmith** [comment]
When I run “docker build” it gets stuck at a step where it asks me to configure my time zone (something to do with tzdata). The program thinks it’s rendering a GUI/dialog in the terminal but it just spits out the menu as ordinary text and there’s no way to select a time zone option and proceed (typing does nothing). What am I doing wrong here?

Edit: I solved this issue by [turning on non-interactive mode](https://stackoverflow.com/questions/22466255/is-it-possible-to-answer-dialog-questions-when-installing-under-docker) for the Docker build process.

**Comment by Frank-Dz** [comment]
```
unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /home/frank/Dockerfile: no such file or directory
```

**Comment by Frank-Dz** [comment]
Already used ```sudo``` command.

**Comment by Frank-Dz** [comment]
> I noticed people were having some issues getting the code to run and ran across some annoying dependency issues myself while setting up the model. I got the dependencies set up and working in docker which should cause less problems.
> 
> If this is something you feel would be appropriate to add to the repository then feel free to do so. If not I won’t be offended :p

Thank you for your great work in making the docker image.

I entered and installed everything, then when I tried to run
```
./run.sh
```
I got  following errors:

```
root@ee27fa041ba4:~/vrn# run.sh
bash: run.sh: command not found
root@ee27fa041ba4:~/vrn# sh run.sh
run.sh: 23: run.sh: pushd: not found
/root/torch/install/bin/luajit: cannot open main.lua: No such file or directory
stack traceback:
        [C]: in function 'dofile'
        /root/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
        [C]: at 0x00405d50
run.sh: 31: run.sh: popd: not found
run.sh: 34: run.sh: pushd: not found
ls: cannot access '*.txt': No such file or directory
run.sh: 75: run.sh: popd: not found
/root/torch/install/bin/luajit: /root/torch/install/share/lua/5.1/trepl/init.lua:389: module 'cunn' not found:No LuaRocks module found for cunn
        no field package.preload['cunn']
        no file '/root/.luarocks/share/lua/5.1/cunn.lua'
        no file '/root/.luarocks/share/lua/5.1/cunn/init.lua'
        no file '/root/torch/install/share/lua/5.1/cunn.lua'
        no file '/root/torch/install/share/lua/5.1/cunn/init.lua'
        no file './cunn.lua'
        no file '/root/torch/install/share/luajit-2.1.0-beta1/cunn.lua'
        no file '/usr/local/share/lua/5.1/cunn.lua'
        no file '/usr/local/share/lua/5.1/cunn/init.lua'
        no file '/root/.luarocks/lib/lua/5.1/cunn.so'
        no file '/root/torch/install/lib/lua/5.1/cunn.so'
        no file '/root/torch/install/lib/cunn.so'
        no file './cunn.so'
        no file '/usr/local/lib/lua/5.1/cunn.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
        [C]: in function 'error'
        /root/torch/install/share/lua/5.1/trepl/init.lua:389: in function 'require'
        process.lua:16: in main chunk
        [C]: in function 'dofile'
        /root/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
        [C]: at 0x00405d50
run.sh: 85: run.sh: pushd: not found
ls: cannot access '*.raw': No such file or directory
run.sh: 91: run.sh: popd: not found
```
Any suggestions?

Thank you very much!

Best,
Frank

**Pull request merged**
